language: cpp
compiler: g++
sudo: required
before_install:
    - sudo add-apt-repository ppa:jonathonf/gcc-7.1
    - sudo apt-get update
    - sudo apt install g++-7
install:
    - cmake .
    - export CXX="g++-7"
script: make