os: Visual Studio 2017
version: 1.1.0.{build}
configuration:
- Debug
- Release
environment:
  matrix:
  - VS_VERSION: 14 2017
    VS_PLATFORM: win32
  - VS_VERSION: 14 2017
    VS_PLATFORM: x64
build:
  project: brynet.sln
  parallel: true
  verbosity: minimal